# As reference: https://medium.com/google-developer-experts/github-actions-for-android-developers-6b54c8a32f55
name: CI

on:
  push:
  workflow_dispatch:
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: oracle

      - name: Build Gradlew
        run: ./gradlew assembleRelease

      - name: Run Kotlin Linter
        run: ./gradlew lint

      - name: Run Unit Tests
        run: ./gradlew testStagingDebugUnitTest

      - name: Export APK
        uses: actions/upload-artifact@v2
        with:
          name: release-apk
          path: app/build/outputs/apk/release/app-release-unsigned.apk

