name: Publish

on:
  release:
    types: [published]
  workflow_dispatch:
  push:
    tags:
      - 'somrepresenta-android-[0-9]+.[0-9]+.[0-9]+'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: 17

      - name: Build Gradlew
        run: ./gradlew assembleRelease

      - name: Release with Notes
        uses: softprops/action-gh-release@v1
        with:
          files: |
            app/build/outputs/apk/release/app-release-unsigned.apk
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


