name: Publish

on:
  release:
    types: [published]
  workflow_dispatch:
  push:
    tags:
      - 'somenergia-ui-[0-9]+.[0-9]+.[0-9]+'                                                  

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Build Gradlew
        run: ./gradlew assembleRelease
      - name: Release with Notes
        uses: softprops/action-gh-release@v1
        with:
          files: |
            app/build/outputs/apk/release/app-release-unsigned.apk
            other/files/as/needed
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


